### PR TITLE
[#8] Allow nested changelogs via `<import>`

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
- [x] CLI test on Ubuntu
 - [ ] CLI test on Mac OS
 - [ ] CLI test on Windows
 - [ ] Maven plugin test
 - [ ] Documentation update

**Comment by fbiville** [comment]
I'm gonna rewrite the documentation in AsciiDoc, so it's gonna be easier to maintain than the current version.

**Comment by sim51** [comment]
Yep it would be cool to used asciidoctor. 
I already used it on other project to make documentation and installation manual. It's very impressive.

**Comment by fbiville** [comment]
Argh, a test is failing on one of the Graphene instance (221) :/

**Comment by fbiville** [comment]
AsciiDoc is not yet officially supported on Github Pages, that's a problem :/

**Comment by sim51** [comment]
We can make a java project that generate a maven site with asciidoctor and deploy it on gh-pages.

**Comment by fbiville** [comment]
That could be nice, yep. Note we need to aggregate the site generated from Asciidoc sources and the Maven plugin site into one single site.

**Pull request merged**
