### PR TITLE
Postcondition 3.x

### PR DESCRIPTION
**Pull request by fpavageau**
This is a port of the 3 squashed commits on `master` from #88 and the extra fix in #96, for the `master_3.x` branch.

The main difference between the `master` and `master_3.x` versions is in the `GraphDatabaseRule` implementations, since `Embedded` and `Remote` have been replaced by `Bolt` and `Http`.

This should close the implementation part of #77.

### CODE REVIEW

**Comment by fbiville** [comment]
Excellent, will merge it ASAP!

**Comment by fpavageau** [comment]
So, between the bug with the Bolt driver not transforming `RuntimeException` into `SQLException` and the bug with the HTTP driver not rolling back local transactions on errors, I can't get the same message in the exception.

I'll change the test to assert the exception and its message differently, instead of trying to have an exact and complete match.

**Comment by fpavageau** [comment]
Finally, it passed!

It looks fine to me now, and we'll be able to rollback 2 changes once a new JDBC driver is released, with the fixes for:
- neo4j-contrib/neo4j-jdbc#23
- neo4j-contrib/neo4j-jdbc#58

**Comment by fbiville** [comment]
Cool, will merge it now!

**Pull request merged**
