### PR TITLE
[#98] Disable auto-commit and restore on close

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by fbiville** [comment]
Hmmm, so it seems we cannot rollback if don't have any open transactions...
Weird thing is this fails only with a JDK 8.

**Comment by fbiville** [comment]
Despite a similar rollback logic, Bolt test passes fine.

**Comment by fbiville** [comment]
(The last commit could actually be cherry-picked to `master`)

**Comment by fpavageau** [comment]
OK, let's see what people have to say about the JDBC driver before determining the course of action.

See neo4j-contrib/neo4j-jdbc#62.

**Comment by mmienko** [comment]
I think I am receiving these by error?

**Comment by fpavageau** [comment]
@mmienko No idea why. Right now you're a participant, but that would be the case anyway once you sent your message. Unsubscribe I guess?

**Pull request merged**
