### PR TITLE
[#40] Separate tx for execution and history insert

### PR DESCRIPTION
**Pull request by fbiville**

### CODE REVIEW

**Comment by sim51** [comment]
For the lock node, what if we create a  neo4j unique contrainst on the lock node  ? 

If we put an attribut that is in fact a constant, and the unique constrainst is enable on this attribut, it's neo4j that avoid the duplication of the node, not us ^^

What do you think  @fbiville ?

**Comment by fbiville** [comment]
Yep, that's right. Good catch!
However, we shouldn't crash the clients that could not succeed to create the node, they still have to wait, so all the lock/condition stuff is still required.

**Comment by fbiville** [comment]
I cleaned up the precondition logic, which was quite unreadable and even misleading + cleaned the unused import.
If the latest changes are OK for you, @sim51, here are the following steps:

```shell
$> git fetch --all -p
$> git checkout issue_40
$> git rebase -i origin/master
# fix up the last commit into the first
$> git push origin issue_40:master
$> git push origin :issue_40
```

Thanks in advance!

**Comment by fbiville** [comment]
By the way, I removed the discussion about lock node. There is another PR for this ;)

**Pull request closed without merging**
