### PR TITLE
Remove logging implementation and configuration

### PR DESCRIPTION
**Pull request by mvitz**
A library should not provide a specific logging implementation if slf4j
is used. It's the library users task to provide a logging
implementation. The same is true for any logging configuration. A
library should not define how my application (who uses the library) uses
logging.

### CODE REVIEW

**Comment by fbiville** [comment]
Thanks for the PR, it's indeed a bad idea to have logback directly in liquigraph-core (shall it be removed entirely from there?).

Maybe it can make sense in Maven plugin / CLI usage context. What do you think?

**Comment by mvitz** [comment]
My opinion is that the core should only rely on slf4j. Providing any slf4j implementation (e.g. logback) and a configuration for tests is fine and normally needed.

CLI is a complete application and uses the library. Therefore CLI should provide a logging implementation and a configuration.

According to https://maven.apache.org/maven-logging.html maven supports slf4j out of the box in it's current versions. Therefore the Maven-Plugin should also only rely on slf4j and not provide it's own logging implementation or configuration.

**Comment by fbiville** [comment]
👍 Agreed!
Would you mind altering your PR to remove explicit reference from core and add Logback to CLI?

**Comment by mvitz** [comment]
I added the reference to `logback-classic` and the same logging configuration as former provided by the `core.jar`.
 Further I removed the `.bat` and `.sh` file from the `cli.jar`

The reference in the `core`-module was set to `test`-scope, to provide some output when testing :-)

**Comment by fbiville** [comment]
Great, I'll wait for the build to complete and merge this.
Thanks a lot!!

**Comment by mvitz** [comment]
Thanks. I hope I didn't break anything in the CLI or Maven-Plugin as I only use the core ;-) If I did let me know and I will take a look at it.

**Comment by fbiville** [comment]
I'll check quickly now. Thanks for your most welcome contribution!

**Comment by fbiville** [comment]
Merged! ;-)

**Pull request closed without merging**
